project:
  type: website
    
website:
  site-url: https://ExpPetroPhil.github.io/
  repo-url: https://github.com/ExpPetroPhil/ExpPetroPhil.github.io/
  favicon: Passbild_Croped.jpg
  title: "Philtastic"
  navbar:
    left:
      - text: "My research"
        href: index.qmd
      - text: "About me"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  
